// PlayerScore types — the data foundation for PlayerIQ.
//
// One PlayerScore document per player, upserted on every estimate call
// (real-time, fire-and-forget) and refreshed nightly by fn-player-score-refresh.
// Stored in Cosmos container `player_trends` (partition /playerId).
//
// playerIQScore = market * 0.60 + performance * 0.40 — never change this
// blend without updating the project brain.

export type PlayerIQDirection = "rising" | "falling" | "stable";
export type Confidence = "high" | "medium" | "low";

export interface MarketScore {
  /** 0-100 derived from broaderTrend impliedTrendPct + recent comp velocity. */
  marketScore: number;
  /** Direction inferred from the median-of-medians of cardSnapshots. */
  marketDirection: PlayerIQDirection;
  /** Average impliedTrendPct across the player's cards, capped ±60. */
  avgTrendPct: number;
  /** Total samples backing this score (sum of cardSnapshots[*].totalSamples). */
  totalSamples: number;
  /** Distinct cardIds contributing to the score. */
  cardCount: number;
  /** Top card by absolute trend movement (for UX surface). */
  topCardName: string | null;
  confidence: Confidence;
}

export interface PerformanceScore {
  /** 0-100 derived from momentum_ratio. 50 = neutral, 100 = on fire. */
  performanceScore: number;
  performanceDirection: PlayerIQDirection;
  /** Recent / baseline ratio from MLB Stats API. 1.0 = neutral. */
  momentumRatio: number;
  /** Short statline e.g. "5G: .333/.421/.667 (3 HR)". */
  statLine: string | null;
  /** "hitting" | "pitching" | null. */
  statGroup: "hitting" | "pitching" | null;
  /** "approaching 500 HR" etc, or null. */
  milestone: string | null;
  confidence: Confidence;
}

export interface PlayerIQScore {
  /** Combined 0-100 score. */
  playerIQScore: number;
  /** UX label per Step 2 rules ("Breakout Watch 🔥", "Heating Up ↑", ...). */
  playerIQLabel: string;
  /** Overall direction from the dominant signal. */
  playerIQDirection: PlayerIQDirection;
}

/**
 * Cosmos document shape stored in `player_trends`.
 * Document id = playerId. Partition key = /playerId.
 */
export interface PlayerScore {
  /** Cosmos document id (matches playerId). */
  id: string;

  // Identity
  /**
   * Cosmos document id and partition key. Two forms exist but they are
   * NOT coequal:
   *   - Numeric MLB id (string), e.g. "545361" for Mike Trout — the
   *     CANONICAL form. Used whenever the MLB Stats API resolver succeeds.
   *   - Slug fallback, e.g. "mike-trout" — TRANSIENT. Used only when MLB
   *     resolution fails at write time (resolver timeout, network error,
   *     player not in MLB's people index yet). Generated by
   *     `playerNameSlug(playerName)`.
   *
   * Slug-form records are auto-merged into the numeric on the next upsert
   * where MLB resolution succeeds (CF-PLAYERTRENDS-DUPLICATE-RECORDS
   * write-path fix shipped same-day as the canonicalization fix at
   * `b51b763`). Persistent slug records should only exist for players
   * whose MLB id has NEVER resolved (minor league pre-call-up, pre-MLB-era,
   * college, etc.). A separate future CF-PLAYERTRENDS-SLUG-RE-RESOLUTION
   * could periodically retry MLB resolution for those orphans; not in
   * scope here.
   *
   * Prior comment ("slug OR mlbId as string") was aspirational — it
   * documented both forms as valid coequal-coexistent, but the system
   * never implemented coexistence. Slug records went orphan after the
   * MLB id later resolved on a subsequent write. The 2026-05-28 dedup
   * fix retroactively cleaned 4 known pairs (Mike Trout, Ken Griffey Jr.,
   * Bobby Cox, John Gil) and added the write-path merge so future
   * dupes don't accrue.
   */
  playerId: string;
  playerName: string;
  mlbPlayerId: number | null;
  team: string | null;
  position: string | null;
  league: "MLB" | "MiLB" | "unknown";
  level: string | null;      // "AAA" / "AA" / null

  // Score components
  market: MarketScore;
  performance: PerformanceScore;

  // Combined
  playerIQScore: number;
  playerIQLabel: string;
  playerIQDirection: PlayerIQDirection;

  // Provenance
  updatedAt: string;            // ISO8601
  dataSource: "realtime_estimate" | "nightly_job" | "manual_seed";
  confidence: Confidence;       // Overall — based on data availability

  // Match/lookup canonical form.
  //
  // CF-PLAYERNAME-CANONICALIZATION (2026-05-28). Computed via
  // canonicalizePlayerName(playerName) on every upsert.
  // getPlayerScoreByName queries this field with an exact-match
  // comparison (indexed) instead of the previous LOWER(playerName)
  // function-call comparison that missed on punctuation / accent
  // differences between caller and stored forms (e.g. "Bobby Witt Jr."
  // vs stored "Bobby Witt Jr", "Acuña" vs stored "Acuna").
  //
  // Optional in the type because legacy stored documents (pre-backfill)
  // don't have it yet; the read path falls back to LOWER(playerName)
  // when the new query returns 0 rows. Field becomes required after
  // the 2026-05-28 backfill commit removes the fallback.
  playerNameNormalized?: string;
}

/**
 * Snapshot of a single card's broaderTrend signal at a point in time.
 * Stored in Cosmos `trend_history` (partition /cardId) by the
 * fire-and-forget writer at the end of computeEstimate().
 *
 * Read by computeMarketScore() to aggregate "all this player's cards
 * over the last 7 days" into a single MarketScore.
 */
export interface TrendSnapshot {
  id: string;                 // `${cardId}_${timestamp}`
  cardId: string;             // partition key
  playerName: string;
  year: number | null;
  set: string | null;
  cardNumber: string | null;
  grade: string;

  // From BroaderTrend
  impliedTrendPct: number;
  direction: "up" | "down" | "flat";
  basedOn: "exact" | "broader" | "insufficient";
  recentMedian: number | null;
  olderMedian: number | null;
  recentCount: number;
  olderCount: number;
  similarCardsScanned: number;
  totalSamples: number;

  // Pricing context at snapshot time
  fairMarketValue: number | null;
  anchorPrice: number | null;

  timestamp: string;          // ISO8601
}

/**
 * Apply the playerIQLabel rules from Step 2.
 *
 *   score >= 80 + rising  → "Breakout Watch 🔥"
 *   score >= 70 + rising  → "Heating Up ↑"
 *   score >= 60 + stable  → "Solid Hold"
 *   score 40-60           → "Watch"
 *   score < 40 + falling  → "Cooling ↓"
 *   score < 30            → "Avoid"
 *   (anything else)       → "Watch"
 */
export function deriveLabel(score: number, direction: PlayerIQDirection): string {
  if (score >= 80 && direction === "rising") return "Breakout Watch 🔥";
  if (score >= 70 && direction === "rising") return "Heating Up ↑";
  if (score >= 60 && direction === "stable") return "Solid Hold";
  if (score < 30) return "Avoid";
  if (score < 40 && direction === "falling") return "Cooling ↓";
  if (score >= 40 && score <= 60) return "Watch";
  return "Watch";
}

/** Slug helper for playerId fallback when MLB id is unknown. */
export function playerNameSlug(name: string): string {
  return name
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

/**
 * Canonical-form playerName for player_trends storage + lookup.
 *
 * CF-PLAYERNAME-CANONICALIZATION (2026-05-28). Composes:
 *   1. Unicode NFKD normalization + combining-mark strip (accents)
 *      \u2014 "Acu\u00f1a" \u2192 "Acuna", "Pe\u00f1a" \u2192 "Pena"
 *   2. Lowercase
 *   3. Punctuation strip (periods, commas, apostrophes including
 *      curly variants) \u2014 "Bobby Witt Jr." \u2192 "Bobby Witt Jr",
 *      "O'Brien" \u2192 "OBrien"
 *   4. Suffix drop (jr|sr|ii|iii|iv with optional trailing period)
 *      \u2014 "Bobby Witt Jr" \u2192 "Bobby Witt"
 *      Both "Bobby Witt Jr." (with period) and "Bobby Witt Jr"
 *      (without) collapse to the same canonical "bobby witt", which
 *      is the entire point of this CF.
 *   5. Whitespace collapse + trim
 *
 * Hyphens are intentionally preserved (Sosa-Lopez vs Sosalopez are
 * different real names).
 *
 * Composition note (not import): the playerResolver.service.ts has a
 * similar `normalizePlayerName` for MLB cache keys. Don't import or
 * mutate it \u2014 that helper drives cache-miss behavior in resolution
 * and any change risks cache thrash. Duplicate the small logic here;
 * the layering (types module, no service deps) is worth the ~5 lines.
 */
export function canonicalizePlayerName(name: string | null | undefined): string {
  if (!name) return "";
  return String(name)
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .replace(/[.,'\u2019\u2018`]/g, "")
    .replace(/\s+(jr|sr|ii|iii|iv)\b\.?/g, "")
    .replace(/\s+/g, " ")
    .trim();
}
