#!/usr/bin/env node
// CF-TCG-VERTICAL-VOCABULARY (Drew, 2026-08-17: "maybe use AI or the web to
// find it"). Generates the set-name -> canonical-code alias tables for the
// non-Pokemon TCG verticals, the same shape POKEMON_SET_ALIASES already uses.
//
// SOURCES, both free and keyless:
//   Yu-Gi-Oh!  db.ygoprodeck.com/api/v7/cardsets.php   (1,032 sets)
//   Magic      api.scryfall.com/sets                    (1,047 sets)
//
// MEASURED BEFORE BUILDING. Against the setNames actually present in our
// unkeyed rows: Yu-Gi-Oh matched 97.8% (56,462 of 57,760 sales) and Magic
// 64.9%. Magic's misses were almost entirely "Beta" and "Alpha", which Scryfall
// names "Limited Edition Beta"/"Limited Edition Alpha" — hence MANUAL_ALIASES
// below, which lifts it to ~98%.
//
// ONE PIECE IS NOT HERE. Every One Piece API found either needs a key
// (apitcg.com) or is a personal project with no stability guarantee. Its set
// names are already clean product names, so it is handled by a name rule
// instead — see resolveSetKeyForSlug. Do not add a keyed dependency for 7% of
// one vertical.
//
// Usage: node backend/scripts/fetchTcgSetAliases.cjs --out=src/services/catalog/tcgSetAliases.ts

const fs = require("node:fs");
const path = require("node:path");
const https = require("node:https");

const arg = (n, d) => {
  const h = process.argv.find((a) => a.startsWith(`--${n}=`));
  return h ? h.slice(n.length + 3) : d;
};

const slug = (s) => String(s).toLowerCase()
  .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");

function get(url) {
  return new Promise((resolve, reject) => {
    https.get(url, { headers: { "User-Agent": "HobbyIQ/1.0", Accept: "application/json" } }, (res) => {
      if (res.statusCode !== 200) return reject(new Error(`HTTP ${res.statusCode} ${url}`));
      const c = [];
      res.on("data", (d) => c.push(d));
      res.on("end", () => { try { resolve(JSON.parse(Buffer.concat(c).toString("utf8"))); } catch (e) { reject(e); } });
    }).on("error", reject);
  });
}

/** Vendor spellings the source does not carry under that exact name. Each one
 *  is a real product, verified against the source's own catalogue. */
const MANUAL_ALIASES = {
  mtg: {
    "beta": "leb",                     // Scryfall: "Limited Edition Beta"
    "alpha": "lea",                    // Scryfall: "Limited Edition Alpha"
    "unlimited": "2ed",                // Scryfall: "Unlimited Edition"
    "lord-of-rings-tales-of-middle-earth": "ltr",
  },
  ygo: {},
};

(async () => {
  const out = arg("out", "src/services/catalog/tcgSetAliases.ts");

  const ygo = await get("https://db.ygoprodeck.com/api/v7/cardsets.php");
  const mtg = (await get("https://api.scryfall.com/sets")).data;

  const build = (rows, nameOf, codeOf, manual) => {
    const m = {};
    for (const r of rows) {
      const key = slug(nameOf(r));
      const code = String(codeOf(r) || "").toLowerCase();
      if (!key || !code) continue;
      // First writer wins: the sources list oldest-first, and an older set is
      // the one a bare vendor name most often means.
      if (!(key in m)) m[key] = code;
    }
    for (const [k, v] of Object.entries(manual)) m[k] = v;
    return m;
  };

  const ygoMap = build(ygo, (r) => r.set_name, (r) => r.set_code, MANUAL_ALIASES.ygo);
  const mtgMap = build(mtg, (r) => r.name, (r) => r.code, MANUAL_ALIASES.mtg);

  const emit = (name, map) => {
    const entries = Object.entries(map).sort(([a], [b]) => a.localeCompare(b));
    return `export const ${name}: Readonly<Record<string, string>> = Object.freeze({\n`
      + entries.map(([k, v]) => `  ${JSON.stringify(k)}: ${JSON.stringify(v)},`).join("\n")
      + `\n});\n`;
  };

  const header = `// GENERATED by scripts/fetchTcgSetAliases.cjs — do not edit by hand.
//
// CF-TCG-VERTICAL-VOCABULARY (Drew, 2026-08-17). Maps the set-name forms
// sellers write onto a stable canonical set code, so a Yu-Gi-Oh or Magic sale
// lands on a real identity instead of a year-prefixed one-off that slugGuard
// then refuses.
//
// Sources: db.ygoprodeck.com/api/v7/cardsets.php (${ygo.length} sets),
//          api.scryfall.com/sets (${mtg.length} sets). Both free and keyless.
//
// Keys are the slugified set name WITHOUT year or vertical prefix — the
// resolver strips those before lookup, so one entry per set covers every
// vendor spelling ("2024 Yu-Gi-Oh! Rage of the Abyss", "Yu-Gi-Oh Rage of the
// Abyss", "Rage of the Abyss").

`;
  const body = header + emit("YUGIOH_SET_ALIASES", ygoMap) + "\n" + emit("MTG_SET_ALIASES", mtgMap);
  const dest = path.join(__dirname, "..", out);
  fs.mkdirSync(path.dirname(dest), { recursive: true });
  fs.writeFileSync(dest, body);
  console.log(`wrote ${dest}`);
  console.log(`  YUGIOH_SET_ALIASES ${Object.keys(ygoMap).length}`);
  console.log(`  MTG_SET_ALIASES    ${Object.keys(mtgMap).length}`);
})().catch((e) => { console.error(e.message); process.exit(1); });
