/**
 * The golden test for the section work: reading MORE sections must not change
 * a single base or parallel row.
 *
 * `only-improve hides well-formed wrong rows` is the reason this is a separate
 * pin rather than a line in the section test. The base ladder for these pages
 * has already been staged and ingested; if widening the reader shifts a rung
 * name, a print run or a player spelling, the change lands as a well-formed
 * row that no later sweep can see, and the pool splits silently.
 *
 * So the base rows are frozen as a checked-in golden file. It was generated by
 * running the scraper at the commit BEFORE the section work (the emit loop
 * untouched), and the section change is only admissible if it reproduces the
 * file byte for byte.
 *
 * To regenerate deliberately (after a ruling that base output SHOULD change):
 *   node backend/tests/helpers/runBcpLaddersOverFixtures.cjs <dir> \
 *     2011_Topps_Chrome=2011-topps-chrome 2021_Topps_Chrome=2021-topps-chrome \
 *     2005_Topps_Chrome=2005-topps-chrome
 *   then keep only the rows whose first column is exactly "base".
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { createRequire } from "node:module";
import { describe, expect, it } from "vitest";

const require_ = createRequire(import.meta.url);

const OUT = path.resolve(
  fs.mkdtempSync(path.join(require_("node:os").tmpdir(), "bcp-golden-pin-")),
);

{
  const { execFileSync } = require_("node:child_process") as typeof import("node:child_process");
  execFileSync(process.execPath, [
    path.resolve(__dirname, "helpers/runBcpLaddersOverFixtures.cjs"), OUT,
    "2011_Topps_Chrome=2011-topps-chrome",
    "2021_Topps_Chrome=2021-topps-chrome",
    "2005_Topps_Chrome=2005-topps-chrome",
  ], { stdio: "pipe" });
}

/**
 * Every base row this run emitted, across every CSV, in a stable order that
 * does not depend on the filesystem's directory ordering.
 */
function baseRowsEmitted(): string {
  const out: string[] = [];
  for (const f of fs.readdirSync(OUT).filter((n) => n.endsWith(".csv")).sort()) {
    const lines = fs.readFileSync(path.join(OUT, f), "utf8").trim().split("\n").slice(1);
    for (const line of lines) if (line.startsWith("base,")) out.push(`${f}\t${line}`);
  }
  return out.join("\n") + "\n";
}

const GOLDEN = path.resolve(__dirname, "fixtures/bcp/base-rows.golden.tsv");

describe("reading every section class leaves base and parallel output untouched", () => {
  it("reproduces the pre-change base rows byte for byte", () => {
    const actual = baseRowsEmitted();
    const expected = fs.readFileSync(GOLDEN, "utf8");
    // Compare line-by-line first so a failure names the row that moved rather
    // than dumping 11,000 lines of diff.
    const a = actual.split("\n"), b = expected.split("\n");
    const firstDiff = a.findIndex((line, i) => line !== b[i]);
    expect({ atLine: firstDiff, actual: a[firstDiff], expected: b[firstDiff] })
      .toEqual({ atLine: -1, actual: undefined, expected: undefined });
    expect(actual).toBe(expected);
  });

  it("the golden file is the real thing, not an empty file that passes vacuously", () => {
    const lines = fs.readFileSync(GOLDEN, "utf8").trim().split("\n");
    expect(lines.length).toBeGreaterThan(10000);
    expect(lines.every((l) => l.includes("\tbase,"))).toBe(true);
  });
});
