// CF-REFERENCE-CATALOG (2026-07-10, Drew) — parseParallelsWorkbook +
// parseSetsWorkbook. Uses a synthetic .xlsx generated by SheetJS in-
// memory (no fixture file on disk) so tests are hermetic.

import { describe, it, expect } from "vitest";
import * as XLSX from "xlsx";
import {
  parseParallelsWorkbook,
  parseSetsWorkbook,
} from "../src/services/reference/referenceParser";

function buildParallelsXlsx(rows: Array<Record<string, string | number>>): Buffer {
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(rows);
  XLSX.utils.book_append_sheet(wb, ws, "Master");
  return XLSX.write(wb, { bookType: "xlsx", type: "buffer" });
}

function buildSetsXlsx(rows: Array<Record<string, string | number>>): Buffer {
  const wb = XLSX.utils.book_new();
  const ws = XLSX.utils.json_to_sheet(rows);
  XLSX.utils.book_append_sheet(wb, ws, "Catalog");
  return XLSX.write(wb, { bookType: "xlsx", type: "buffer" });
}

const NOW = () => "2026-07-10T00:00:00.000Z";

describe("parseParallelsWorkbook", () => {
  it("parses a well-formed Bowman-style workbook end-to-end", () => {
    const buf = buildParallelsXlsx([
      {
        Year: 2026,
        Product: "Bowman",
        "Card Set": "Chrome Prospect Autographs",
        Parallel: "Red Refractor",
        "Print Run": 5,
        Numbered: "Yes",
        Auto: "Y",
        Confidence: "High",
        Notes: "",
      },
      {
        Year: 2026,
        Product: "Bowman",
        "Card Set": "Chrome Prospect Autographs",
        Parallel: "Superfractor",
        "Print Run": 1,
        Numbered: "Yes",
        Auto: "Y",
        Confidence: "Verified",
        Notes: "",
      },
    ]);
    const { docs, sheetRowCount, skipped } = parseParallelsWorkbook(buf, { now: NOW });
    expect(sheetRowCount).toBe(2);
    expect(skipped).toBe(0);
    expect(docs).toHaveLength(2);
    const red = docs.find((d) => d.parallel === "Red Refractor")!;
    expect(red.docType).toBe("parallel");
    expect(red.year).toBe(2026);
    expect(red.printRun).toBe(5);
    expect(red.numbered).toBe(true);
    expect(red.auto).toBe(true);
    expect(red.confidence).toBe("High");
    expect(red.licensed).toBe(true);
    expect(red.productKey).toBe("bowman");
    expect(red.cardSetKey).toBe("chrome-prospect-autographs");
    expect(red.parallelKey).toBe("red-refractor");
    expect(red.updatedAt).toBe(NOW());
    expect(red.schemaVersion).toBe(1);
    expect(red.sourceUrl).toBeNull();
  });

  it("derives runVaries when Numbered=Yes AND Print Run is blank", () => {
    const buf = buildParallelsXlsx([
      {
        Year: 2005,
        Product: "Bowman Sterling",
        "Card Set": "Base",
        Parallel: "Refractor",
        "Print Run": "",
        Numbered: "Yes",
        Auto: "N",
        Confidence: "Medium",
        Notes: "Print run varies by card",
      },
    ]);
    const { docs } = parseParallelsWorkbook(buf, { now: NOW });
    expect(docs).toHaveLength(1);
    expect(docs[0].runVaries).toBe(true);
    expect(docs[0].printRun).toBeNull();
  });

  it("derives perCardRun when notes contain 'PER-CARD'; printRun always null on those rows", () => {
    const buf = buildParallelsXlsx([
      {
        Year: 2001,
        Product: "Donruss",
        "Card Set": "Essential Credentials",
        Parallel: "Now",
        "Print Run": 100, // even if a stray number is present, perCardRun forces null
        Numbered: "Yes",
        Auto: "N",
        Confidence: "High",
        Notes: "Print run PER-CARD (variable per player)",
      },
    ]);
    const { docs } = parseParallelsWorkbook(buf, { now: NOW });
    expect(docs).toHaveLength(1);
    expect(docs[0].perCardRun).toBe(true);
    expect(docs[0].printRun).toBeNull();
  });

  it("derives licensed=false for the unlicensed manufacturers list", () => {
    const buf = buildParallelsXlsx([
      { Year: 2020, Product: "Panini Prizm", "Card Set": "Base", Parallel: "Red Prizm", "Print Run": 299, Numbered: "Yes", Auto: "N", Confidence: "Verified", Notes: "" },
      { Year: 2020, Product: "Leaf Metal Draft", "Card Set": "Base", Parallel: "Gold", "Print Run": 20, Numbered: "Yes", Auto: "Y", Confidence: "High", Notes: "" },
      { Year: 2020, Product: "TRISTAR Obak", "Card Set": "Base", Parallel: "Red", "Print Run": 25, Numbered: "Yes", Auto: "N", Confidence: "Medium", Notes: "" },
      { Year: 2020, Product: "Onyx Vintage", "Card Set": "Auto", Parallel: "Gold", "Print Run": 25, Numbered: "Yes", Auto: "Y", Confidence: "High", Notes: "" },
      { Year: 2020, Product: "Bowman", "Card Set": "Chrome", Parallel: "Gold Refractor", "Print Run": 50, Numbered: "Yes", Auto: "N", Confidence: "Verified", Notes: "" },
    ]);
    const { docs } = parseParallelsWorkbook(buf, { now: NOW });
    const byProduct = Object.fromEntries(docs.map((d) => [d.product, d.licensed]));
    expect(byProduct["Panini Prizm"]).toBe(false);
    expect(byProduct["Leaf Metal Draft"]).toBe(false);
    expect(byProduct["TRISTAR Obak"]).toBe(false);
    expect(byProduct["Onyx Vintage"]).toBe(false);
    expect(byProduct["Bowman"]).toBe(true);
  });

  it("skips rows with missing required fields (year / product / cardSet / parallel)", () => {
    const buf = buildParallelsXlsx([
      { Year: 2026, Product: "Bowman", "Card Set": "Chrome", Parallel: "Red", "Print Run": 5, Numbered: "Yes", Auto: "N", Confidence: "High", Notes: "" },
      { Year: "", Product: "Bowman", "Card Set": "Chrome", Parallel: "Blue", "Print Run": 150, Numbered: "Yes", Auto: "N", Confidence: "High", Notes: "" },
      { Year: 2026, Product: "", "Card Set": "Chrome", Parallel: "Green", "Print Run": 99, Numbered: "Yes", Auto: "N", Confidence: "High", Notes: "" },
      { Year: 2026, Product: "Bowman", "Card Set": "", Parallel: "Gold", "Print Run": 50, Numbered: "Yes", Auto: "N", Confidence: "High", Notes: "" },
      { Year: 2026, Product: "Bowman", "Card Set": "Chrome", Parallel: "", "Print Run": 5, Numbered: "Yes", Auto: "N", Confidence: "High", Notes: "" },
    ]);
    const { docs, skipped, sheetRowCount } = parseParallelsWorkbook(buf, { now: NOW });
    expect(sheetRowCount).toBe(5);
    expect(docs).toHaveLength(1);
    expect(skipped).toBe(4);
  });

  it("deterministic ids — same tuple → same doc.id across runs", () => {
    const rows = [{ Year: 2026, Product: "Bowman", "Card Set": "Chrome", Parallel: "Red", "Print Run": 5, Numbered: "Yes", Auto: "N", Confidence: "High", Notes: "" }];
    const buf = buildParallelsXlsx(rows);
    const a = parseParallelsWorkbook(buf, { now: NOW });
    const b = parseParallelsWorkbook(buf, { now: NOW });
    expect(a.docs[0].id).toBe(b.docs[0].id);
  });
});

describe("parseSetsWorkbook", () => {
  it("parses a vintage-set-catalog row", () => {
    const buf = buildSetsXlsx([
      {
        "Year Text": "1909-11",
        "Set Name": "T206",
        Manufacturer: "American Tobacco Company",
        Type: "Tobacco",
        "Set Size": 524,
        Format: "Card",
        Notes: "Iconic pre-war release; Honus Wagner rarity",
        Confidence: "Verified",
      },
    ]);
    const { docs, skipped, sheetRowCount } = parseSetsWorkbook(buf, { now: NOW });
    expect(sheetRowCount).toBe(1);
    expect(skipped).toBe(0);
    expect(docs).toHaveLength(1);
    const s = docs[0];
    expect(s.docType).toBe("set");
    expect(s.yearText).toBe("1909-11");
    expect(s.sortYear).toBe(1909);
    expect(s.setName).toBe("T206");
    expect(s.setSize).toBe(524);
    expect(s.productKey).toBe("t206");
  });

  it("accepts the vintage-catalog header variants (Year(s) / Set / Key Notes)", () => {
    // Header regression: production vintage_set_catalog_1887_1988.xlsx uses
    // "Year(s)" (not "Year Text"), bare "Set" (not "Set Name"), and "Key
    // Notes" (not "Notes"). The initial dry-run skipped 158/158 rows
    // because the alias map missed these.
    const buf = buildSetsXlsx([
      {
        "Year(s)": 1887,
        Set: "N172 Old Judge",
        Manufacturer: "Goodwin & Co.",
        Type: "Tobacco",
        "Set Size": "",
        Format: "Sepia photo cards",
        "Key Notes": "500+ subjects; no definitive set size",
        Confidence: "High",
      },
    ]);
    const { docs, skipped, sheetRowCount } = parseSetsWorkbook(buf, { now: NOW });
    expect(sheetRowCount).toBe(1);
    expect(skipped).toBe(0);
    expect(docs).toHaveLength(1);
    expect(docs[0].setName).toBe("N172 Old Judge");
    expect(docs[0].yearText).toBe("1887");
    expect(docs[0].notes).toContain("500+ subjects");
  });

  it("sortYear extracts first 4-digit year from multi-year yearText", () => {
    const buf = buildSetsXlsx([
      { "Year Text": "1949-52", "Set Name": "Bowman Baseball", Manufacturer: "Bowman", Type: "Major", "Set Size": 240, Format: "Card", Notes: "", Confidence: "High" },
      { "Year Text": "1961", "Set Name": "Post Cereal", Manufacturer: "Post", Type: "Food", "Set Size": 200, Format: "Panel", Notes: "", Confidence: "Medium" },
    ]);
    const { docs } = parseSetsWorkbook(buf, { now: NOW });
    expect(docs.find((d) => d.setName === "Bowman Baseball")!.sortYear).toBe(1949);
    expect(docs.find((d) => d.setName === "Post Cereal")!.sortYear).toBe(1961);
  });
});
