// Parallel multipliers for Bowman, Topps, and related product families
// All keys and parallels should be lowercase for normalization

export type ProductFamily =
  | "Bowman"
  | "Bowman Chrome"
  | "Bowman Draft"
  | "Bowman Chrome Auto"
  | "Topps Chrome"
  | "Topps Chrome Update"
  | "Topps"
  | "Topps Flagship"
  | "Topps Paper";

export interface ParallelConfig {
  [productFamily: string]: {
    [parallel: string]: number;
  };
}

export const parallelMultipliers: ParallelConfig = {
  "bowman": {
    "base": 1.0,
    "refractor": 1.2,
    "x-fractor": 1.3,
    "shimmer": 1.25,
    "mini diamond": 1.22,
    "speckle": 1.18,
    "lunar glow": 1.15,
    "lava": 1.3,
    "blue": 1.5,
    "blue shimmer": 1.55,
    "blue wave": 1.52,
    "blue mojo": 1.53,
    "blue mini diamond": 1.51,
    "blue refractor": 1.5,
    "green": 1.7,
    "green shimmer": 1.75,
    "green wave": 1.72,
    "green mojo": 1.73,
    "green refractor": 1.7,
    "yellow": 1.8,
    "yellow lava": 1.85,
    "gold": 2.0,
    "gold shimmer": 2.05,
    "gold wave": 2.02,
    "gold mini diamond": 2.01,
    "gold refractor": 2.0,
    "orange": 3.0,
    "orange shimmer": 3.05,
    "orange wave": 3.02,
    "orange mojo": 3.01,
    "orange refractor": 3.0,
    "red": 5.0,
    "red lava": 5.1,
    "red wave": 5.05,
    "red refractor": 5.0,
    "rose gold": 2.2,
    "purple": 1.4,
    "purple shimmer": 1.45,
    "purple refractor": 1.4,
    "aqua": 1.3,
    "aqua lava": 1.35,
    "aqua refractor": 1.3,
    "sapphire": 2.5,
    "sapphire blue": 2.7,
    "sapphire green": 2.8,
    "sapphire gold": 3.2,
    "sapphire orange": 4.0,
    "sapphire red": 6.0,
    "sapphire purple": 3.0,
    "sapphire black": 7.0,
    "black": 2.3,
    "pink": 1.25,
    "pink refractor": 1.25,
    "pink wave": 1.27,
    "mojo": 1.2,
    "raywave": 1.22,
    "reptilian": 1.3,
    "atomic": 1.35,
    "fuchsia": 1.15,
    "sepia": 1.1,
    "negative": 1.1,
    "image variation": 1.5,
    "superfractor": 20.0,
    "printing plate": 10.0
  },
  "bowman chrome": {
    "base": 1.0,
    "refractor": 1.2,
    "x-fractor": 1.3,
    "shimmer": 1.25,
    "mini diamond": 1.22,
    "speckle": 1.18,
    "lunar glow": 1.15,
    "lava": 1.3,
    "blue": 1.5,
    "blue shimmer": 1.55,
    "blue wave": 1.52,
    "blue mojo": 1.53,
    "blue mini diamond": 1.51,
    "blue refractor": 1.5,
    "green": 1.7,
    "green shimmer": 1.75,
    "green wave": 1.72,
    "green mojo": 1.73,
    "green refractor": 1.7,
    "yellow": 1.8,
    "yellow lava": 1.85,
    "gold": 2.0,
    "gold shimmer": 2.05,
    "gold wave": 2.02,
    "gold mini diamond": 2.01,
    "gold refractor": 2.0,
    "orange": 3.0,
    "orange shimmer": 3.05,
    "orange wave": 3.02,
    "orange mojo": 3.01,
    "orange refractor": 3.0,
    "red": 5.0,
    "red lava": 5.1,
    "red wave": 5.05,
    "red refractor": 5.0,
    "rose gold": 2.2,
    "purple": 1.4,
    "purple shimmer": 1.45,
    "purple refractor": 1.4,
    "aqua": 1.3,
    "aqua lava": 1.35,
    "aqua refractor": 1.3,
    "sapphire": 2.5,
    "sapphire blue": 2.7,
    "sapphire green": 2.8,
    "sapphire gold": 3.2,
    "sapphire orange": 4.0,
    "sapphire red": 6.0,
    "sapphire purple": 3.0,
    "sapphire black": 7.0,
    "black": 2.3,
    "pink": 1.25,
    "pink refractor": 1.25,
    "pink wave": 1.27,
    "mojo": 1.2,
    "raywave": 1.22,
    "reptilian": 1.3,
    "atomic": 1.35,
    "fuchsia": 1.15,
    "sepia": 1.1,
    "negative": 1.1,
    "image variation": 1.5,
    "superfractor": 20.0,
    "printing plate": 10.0
  },
  "bowman draft": {
    "base": 1.0,
    "refractor": 1.2,
    "x-fractor": 1.3,
    "shimmer": 1.25,
    "mini diamond": 1.22,
    "speckle": 1.18,
    "lunar glow": 1.15,
    "lava": 1.3,
    "blue": 1.5,
    "blue shimmer": 1.55,
    "blue wave": 1.52,
    "blue mojo": 1.53,
    "blue mini diamond": 1.51,
    "blue refractor": 1.5,
    "green": 1.7,
    "green shimmer": 1.75,
    "green wave": 1.72,
    "green mojo": 1.73,
    "green refractor": 1.7,
    "yellow": 1.8,
    "yellow lava": 1.85,
    "gold": 2.0,
    "gold shimmer": 2.05,
    "gold wave": 2.02,
    "gold mini diamond": 2.01,
    "gold refractor": 2.0,
    "orange": 3.0,
    "orange shimmer": 3.05,
    "orange wave": 3.02,
    "orange mojo": 3.01,
    "orange refractor": 3.0,
    "red": 5.0,
    "red lava": 5.1,
    "red wave": 5.05,
    "red refractor": 5.0,
    "rose gold": 2.2,
    "purple": 1.4,
    "purple shimmer": 1.45,
    "purple refractor": 1.4,
    "aqua": 1.3,
    "aqua lava": 1.35,
    "aqua refractor": 1.3,
    "sapphire": 2.5,
    "sapphire blue": 2.7,
    "sapphire green": 2.8,
    "sapphire gold": 3.2,
    "sapphire orange": 4.0,
    "sapphire red": 6.0,
    "sapphire purple": 3.0,
    "sapphire black": 7.0,
    "black": 2.3,
    "pink": 1.25,
    "pink refractor": 1.25,
    "pink wave": 1.27,
    "mojo": 1.2,
    "raywave": 1.22,
    "reptilian": 1.3,
    "atomic": 1.35,
    "fuchsia": 1.15,
    "sepia": 1.1,
    "negative": 1.1,
    "image variation": 1.5,
    "superfractor": 20.0,
    "printing plate": 10.0
  },
  "bowman chrome auto": {
    "base": 1.0,
    "refractor": 1.3,
    "blue": 1.7,
    "green": 2.0,
    "gold": 2.5,
    "orange": 4.0,
    "red": 7.0,
    "superfractor": 25.0,
    "printing plate": 12.0
  },
  "topps chrome": {
    "base": 1.0,
    "refractor": 1.2,
    "prism refractor": 1.25,
    "x-fractor": 1.3,
    "sepia": 1.1,
    "raywave": 1.22,
    "pink": 1.15,
    "pink refractor": 1.15,
    "purple": 1.4,
    "purple refractor": 1.4,
    "blue": 1.5,
    "blue raywave": 1.55,
    "blue refractor": 1.5,
    "green": 1.7,
    "green refractor": 1.7,
    "green wave": 1.72,
    "aqua": 1.3,
    "aqua lava": 1.35,
    "aqua refractor": 1.3,
    "gold": 2.0,
    "gold wave": 2.02,
    "gold refractor": 2.0,
    "orange": 3.0,
    "orange wave": 3.02,
    "orange refractor": 3.0,
    "red": 5.0,
    "red wave": 5.05,
    "red refractor": 5.0,
    "black": 2.3,
    "black refractor": 2.3,
    "negative": 1.1,
    "rose gold": 2.2,
    "rose gold mini diamond": 2.25,
    "magenta": 1.12,
    "magenta speckle": 1.13,
    "magenta lava": 1.14,
    "superfractor": 20.0,
    "printing plate": 10.0,
    "image variation": 1.5
  },
  "topps chrome update": {
    "base": 1.0,
    "refractor": 1.2,
    "prism refractor": 1.25,
    "x-fractor": 1.3,
    "sepia": 1.1,
    "raywave": 1.22,
    "pink": 1.15,
    "pink refractor": 1.15,
    "purple": 1.4,
    "purple refractor": 1.4,
    "blue": 1.5,
    "blue raywave": 1.55,
    "blue refractor": 1.5,
    "green": 1.7,
    "green refractor": 1.7,
    "green wave": 1.72,
    "aqua": 1.3,
    "aqua lava": 1.35,
    "aqua refractor": 1.3,
    "gold": 2.0,
    "gold wave": 2.02,
    "gold refractor": 2.0,
    "orange": 3.0,
    "orange wave": 3.02,
    "orange refractor": 3.0,
    "red": 5.0,
    "red wave": 5.05,
    "red refractor": 5.0,
    "black": 2.3,
    "black refractor": 2.3,
    "negative": 1.1,
    "rose gold": 2.2,
    "rose gold mini diamond": 2.25,
    "magenta": 1.12,
    "magenta speckle": 1.13,
    "magenta lava": 1.14,
    "superfractor": 20.0,
    "printing plate": 10.0,
    "image variation": 1.5
  },
  "topps": {
    "base": 1.0,
    "flagship": 1.0,
    "paper": 1.0
  },
  "topps flagship": {
    "base": 1.0,
    "flagship": 1.0,
    "paper": 1.0
  },
  "topps paper": {
    "base": 1.0,
    "flagship": 1.0,
    "paper": 1.0
  }
};
