import { Router } from "express";
import { readFileSync } from "fs";
import { resolve } from "path";

const router = Router();

// ── CF-DEPLOY-SCRIPT-RESTART-FIX — code-baked build-info ─────────────────
//
// dist/build-info.json is generated by scripts/write-build-info.cjs at
// `npm run build` time (postbuild step in the build chain). It contains
// the git SHA baked from the BUILD ARTIFACT, distinct from the GIT_SHA
// env var that gets set by the deploy script at [1/5].
//
// Why both? /api/health.build.shaShort reads from env (set BEFORE deploy
// completes), so it reports the new SHA even if the new dist never loads.
// The 3-for-3 silent old-dist deploys this session (095deb2, cbfd963,
// 150d14b) all passed shaShort verification while serving the OLD dist.
// shaFromCode reads from a file inside dist/ — it CANNOT match the new
// SHA unless the new dist is actually loaded. The deploy script polls
// shaFromCode to detect TRUE dist swap.
//
// Module-load read + cache: build-info.json doesn't change between
// restarts of a given container instance, so we read once at module
// init. Missing file → shaFromCode = null (test fixtures, pre-postbuild
// containers, anything missing the new build-info path).
//
// __dirname is the CommonJS-emitted module's directory. tsc with
// module: NodeNext + no "type: module" in package.json emits CJS,
// where __dirname is a runtime global. Matches existing pattern in
// src/agents/beckett/sweepOrchestrator.ts.

interface BuildInfo {
  sha: string;
  shaShort: string;
  branch: string;
  builtAt: string;
}

function loadBuildInfo(): BuildInfo | null {
  // dist/routes/health.routes.js → ../build-info.json = dist/build-info.json
  // For tests running against compiled .ts under vitest, the same relative
  // resolution lands in src/routes/.. = src/build-info.json which doesn't
  // exist and gracefully returns null.
  const candidate = resolve(__dirname, "..", "build-info.json");
  try {
    const raw = readFileSync(candidate, "utf8");
    const parsed = JSON.parse(raw);
    if (
      parsed &&
      typeof parsed.sha === "string" &&
      typeof parsed.shaShort === "string"
    ) {
      return parsed as BuildInfo;
    }
    return null;
  } catch {
    return null;
  }
}

const BUILD_INFO: BuildInfo | null = loadBuildInfo();

router.get(["/", ""], (req, res) => {
  res.json({
    ok: true,
    status: "ok",
    service: "HobbyIQ API",
    brand: "HobbyIQ",
    port: Number(process.env.PORT || 8080),
    environment: process.env.NODE_ENV || "production",
    timestamp: new Date().toISOString(),
    services: {
      cosmos: !!process.env.COSMOS_ENDPOINT ? "configured" : "fallback",
      redis: !!process.env.REDIS_HOST ? "configured" : "fallback",
      appInsights: !!process.env.APPLICATIONINSIGHTS_CONNECTION_STRING ? "active" : "off",
    },
    // Build metadata. Two distinct SHA paths:
    //   - shaShort / sha / branch / deployedAt: read from env vars set by
    //     the deploy script at [1/5]. Reflects what was REQUESTED, not
    //     what's actually running. Kept for backwards compat.
    //   - shaFromCode / shaFromCodeShort / branchFromCode / builtAt: read
    //     from dist/build-info.json baked at `npm run build` time. ONLY
    //     present in dist that has actually been loaded by the running
    //     process. This is the deploy-verification signal.
    build: {
      sha: process.env.GIT_SHA || "unknown",
      shaShort: process.env.GIT_SHA_SHORT || "unknown",
      branch: process.env.GIT_BRANCH || "unknown",
      deployedAt: process.env.DEPLOYED_AT || "unknown",
      // CF-DEPLOY-SCRIPT-RESTART-FIX additions:
      shaFromCode: BUILD_INFO?.sha ?? null,
      shaFromCodeShort: BUILD_INFO?.shaShort ?? null,
      branchFromCode: BUILD_INFO?.branch ?? null,
      builtAt: BUILD_INFO?.builtAt ?? null,
    },
  });
});

export default router;
