import { Router } from "express";
import { readFileSync } from "fs";
import { resolve } from "path";
// CF-HEALTH-DEEP-P1 (Drew, 2026-07-26). /api/health/deep probes actual
// downstream dependencies (Cosmos reachability + critical envs). The
// shallow /api/health above just says "process is alive" — deep says
// "process is READY to serve traffic". Ops-monitoring should hit deep
// for meaningful alarms; App Service liveness stays on shallow so a
// dep blip doesn't kill the container.
import { getPortfolioContainer } from "../services/portfolioiq/portfolioStore.service.js";

const router = Router();

const PROBE_TIMEOUT_MS = 3_000;

async function withTimeout<T>(p: Promise<T>, ms: number): Promise<T> {
  return await Promise.race([
    p,
    new Promise<T>((_, reject) =>
      setTimeout(() => reject(new Error(`probe timed out after ${ms}ms`)), ms),
    ),
  ]);
}

async function probeCosmos(): Promise<{ status: "ok" | "degraded" | "down"; latencyMs: number; error?: string }> {
  const t0 = Date.now();
  try {
    const container = await withTimeout(getPortfolioContainer(), PROBE_TIMEOUT_MS);
    if (!container) {
      return { status: "down", latencyMs: Date.now() - t0, error: "container unavailable" };
    }
    // Cheapest reachability signal: point-read on a synthetic id.
    // Cosmos returns 404 quickly (single RU); anything else is degradation.
    try {
      await withTimeout(
        container.item("__healthprobe__", "__healthprobe__").read(),
        PROBE_TIMEOUT_MS,
      );
    } catch (err: any) {
      if (err?.code === 404 || err?.statusCode === 404) {
        return { status: "ok", latencyMs: Date.now() - t0 };
      }
      throw err;
    }
    return { status: "ok", latencyMs: Date.now() - t0 };
  } catch (err: any) {
    return {
      status: "down",
      latencyMs: Date.now() - t0,
      error: err?.message ?? String(err),
    };
  }
}

// ── CF-DEPLOY-SCRIPT-RESTART-FIX — code-baked build-info ─────────────────
//
// dist/build-info.json is generated by scripts/write-build-info.cjs at
// `npm run build` time (postbuild step in the build chain). It contains
// the git SHA baked from the BUILD ARTIFACT, distinct from the GIT_SHA
// env var that gets set by the deploy script at [1/5].
//
// Why both? /api/health.build.shaShort reads from env (set BEFORE deploy
// completes), so it reports the new SHA even if the new dist never loads.
// The 3-for-3 silent old-dist deploys this session (095deb2, cbfd963,
// 150d14b) all passed shaShort verification while serving the OLD dist.
// shaFromCode reads from a file inside dist/ — it CANNOT match the new
// SHA unless the new dist is actually loaded. The deploy script polls
// shaFromCode to detect TRUE dist swap.
//
// Module-load read + cache: build-info.json doesn't change between
// restarts of a given container instance, so we read once at module
// init. Missing file → shaFromCode = null (test fixtures, pre-postbuild
// containers, anything missing the new build-info path).
//
// __dirname is the CommonJS-emitted module's directory. tsc with
// module: NodeNext + no "type: module" in package.json emits CJS,
// where __dirname is a runtime global. Matches existing pattern in
// src/agents/beckett/sweepOrchestrator.ts.

interface BuildInfo {
  sha: string;
  shaShort: string;
  branch: string;
  builtAt: string;
}

function loadBuildInfo(): BuildInfo | null {
  // dist/routes/health.routes.js → ../build-info.json = dist/build-info.json
  // For tests running against compiled .ts under vitest, the same relative
  // resolution lands in src/routes/.. = src/build-info.json which doesn't
  // exist and gracefully returns null.
  const candidate = resolve(__dirname, "..", "build-info.json");
  try {
    const raw = readFileSync(candidate, "utf8");
    const parsed = JSON.parse(raw);
    if (
      parsed &&
      typeof parsed.sha === "string" &&
      typeof parsed.shaShort === "string"
    ) {
      return parsed as BuildInfo;
    }
    return null;
  } catch {
    return null;
  }
}

const BUILD_INFO: BuildInfo | null = loadBuildInfo();

router.get(["/", ""], (req, res) => {
  res.json({
    ok: true,
    status: "ok",
    service: "HobbyIQ API",
    brand: "HobbyIQ",
    port: Number(process.env.PORT || 8080),
    environment: process.env.NODE_ENV || "production",
    timestamp: new Date().toISOString(),
    services: {
      cosmos: !!process.env.COSMOS_ENDPOINT ? "configured" : "fallback",
      redis: !!process.env.REDIS_HOST ? "configured" : "fallback",
      appInsights: !!process.env.APPLICATIONINSIGHTS_CONNECTION_STRING ? "active" : "off",
    },
    // Build metadata. Two distinct SHA paths:
    //   - shaShort / sha / branch / deployedAt: read from env vars set by
    //     the deploy script at [1/5]. Reflects what was REQUESTED, not
    //     what's actually running. Kept for backwards compat.
    //   - shaFromCode / shaFromCodeShort / branchFromCode / builtAt: read
    //     from dist/build-info.json baked at `npm run build` time. ONLY
    //     present in dist that has actually been loaded by the running
    //     process. This is the deploy-verification signal.
    build: {
      sha: process.env.GIT_SHA || "unknown",
      shaShort: process.env.GIT_SHA_SHORT || "unknown",
      branch: process.env.GIT_BRANCH || "unknown",
      deployedAt: process.env.DEPLOYED_AT || "unknown",
      // CF-DEPLOY-SCRIPT-RESTART-FIX additions:
      shaFromCode: BUILD_INFO?.sha ?? null,
      shaFromCodeShort: BUILD_INFO?.shaShort ?? null,
      branchFromCode: BUILD_INFO?.branch ?? null,
      builtAt: BUILD_INFO?.builtAt ?? null,
    },
  });
});

// CF-HEALTH-DEEP-P1 (Drew, 2026-07-26). Readiness probe. Returns 200
// when the process is ready to serve production traffic (Cosmos
// reachable + all critical envs set); 503 when a critical dependency
// is down or missing. Intended for ops-monitoring dashboards, NOT for
// App Service liveness (that stays on shallow /api/health — a transient
// Cosmos blip should not cause App Service to kill and restart the
// container, which would just move the failure without fixing it).
router.get("/deep", async (_req, res) => {
  const t0 = Date.now();

  const [cosmos] = await Promise.all([probeCosmos()]);

  const criticalEnvsMissing: string[] = [];
  if (!process.env.COSMOS_CONNECTION_STRING && !process.env.COSMOS_ENDPOINT) {
    criticalEnvsMissing.push("COSMOS_CONNECTION_STRING/COSMOS_ENDPOINT");
  }
  if (!process.env.AUTH_SESSION_SECRET) {
    criticalEnvsMissing.push("AUTH_SESSION_SECRET");
  }
  if (!process.env.CARD_HEDGE_API_KEY) {
    criticalEnvsMissing.push("CARD_HEDGE_API_KEY");
  }

  const recommendedEnvsMissing: string[] = [];
  if (!process.env.APPLICATIONINSIGHTS_CONNECTION_STRING) {
    recommendedEnvsMissing.push("APPLICATIONINSIGHTS_CONNECTION_STRING");
  }
  if (!process.env.CARDSIGHT_API_KEY) {
    recommendedEnvsMissing.push("CARDSIGHT_API_KEY");
  }

  const ok = cosmos.status === "ok" && criticalEnvsMissing.length === 0;
  const status = ok
    ? "healthy"
    : cosmos.status === "down" || criticalEnvsMissing.length > 0
      ? "down"
      : "degraded";

  const body = {
    ok,
    status,
    uptimeSec: Math.floor(process.uptime()),
    totalLatencyMs: Date.now() - t0,
    timestamp: new Date().toISOString(),
    build: {
      shaShort: process.env.GIT_SHA_SHORT || "unknown",
      shaFromCodeShort: BUILD_INFO?.shaShort ?? null,
    },
    checks: {
      cosmos,
      config: {
        status: criticalEnvsMissing.length === 0 ? "ok" : "down",
        criticalEnvsMissing,
        recommendedEnvsMissing,
      },
    },
  };

  res.status(ok ? 200 : 503).json(body);
});

export default router;
