param(
    [Parameter(Mandatory=$true)]
    [string]$ResourceGroup,
    [Parameter(Mandatory=$true)]
    [string]$AppName,
    [string]$BackendPath = "./backend",
    [string]$ZipPath = "./deploy.zip"
)

$ErrorActionPreference = "Stop"

Write-Host "[INFO] Building backend at $BackendPath..."
if (Test-Path "$BackendPath/package-lock.json") {
    npm install --prefix $BackendPath
} else {
    npm install --prefix $BackendPath --package-lock-only
}

if (Test-Path "$BackendPath/package.json") {
    $pkg = Get-Content "$BackendPath/package.json" | ConvertFrom-Json
    if ($pkg.scripts.build) {
        npm run build --prefix $BackendPath
    }
}

Write-Host "[INFO] Building deploy ZIP with node zip.js..."
if ($ZipPath -ne "./deploy.zip") {
    Write-Host "[WARN] Custom ZipPath '$ZipPath' was provided. This script now standardizes on ./deploy.zip generated by zip.js."
}

node ./zip.js
if ($LASTEXITCODE -ne 0) {
    Write-Host "[FAIL] zip.js failed (exit code $LASTEXITCODE)."
    exit 1
}

$resolvedZipPath = (Resolve-Path "./deploy.zip").Path
Write-Host "[INFO] Deploying ZIP to Azure App Service from $resolvedZipPath..."
$deployRaw = az webapp deploy --resource-group $ResourceGroup --name $AppName --src-path $resolvedZipPath --type zip --restart true --only-show-errors --output json

if ($LASTEXITCODE -ne 0) {
    Write-Host "[FAIL] az webapp deploy command failed (exit code $LASTEXITCODE)."
    exit 1
}

$deploy = $deployRaw | ConvertFrom-Json
$status = if ($deploy.properties -and $deploy.properties.status) { $deploy.properties.status } elseif ($deploy.status) { $deploy.status } else { "Unknown" }

if ($status -eq "RuntimeSuccessful" -or $status -eq "Success") {
    Write-Host "[PASS] ZIP deploy succeeded ($status)."
    Write-Host "[INFO] Smoke test:"
    Write-Host ".\\scripts\\smoke-test-azure.ps1 -BaseUrl \"https://$AppName.azurewebsites.net\""
    exit 0
}

Write-Host "[FAIL] ZIP deploy failed (status: $status)."
$deploy | ConvertTo-Json -Depth 8 | Write-Host
exit 1
