// AUTO-GENERATED by backend/scripts/grade-calibrate.mjs
// Do not hand-edit; overwritten by the Grade Calibration Refresh workflow.
// Human-maintained code (lookupGradeRatio, classifyFamily) lives in
// gradeCalibrationConfig.ts and imports the constants exported here.
//
// Generation source: 365d rolling window of ch_daily_sales,
// per-family per-year partitioned queries to fit Cosmos serverless
// RU budget on the big families (topps, topps-chrome, bowman, etc.).

export interface GradeCalibrationTierEntry {
  medianRatio: number;
  sampleSize: number;
}

export interface GradeCalibrationEntry {
  medianRatio: number;
  p25: number;
  p75: number;
  sampleSize: number;
  // Empirical per-grade-tier ratios keyed by numeric grade as string
  // (e.g. "10", "9.5", "9"). Optional; present only when >=20 paired-
  // sale samples exist at that specific tier. Absent until the next
  // Grade Calibration Refresh workflow run rebuilds the data.
  // See CF-GRADE-CALIBRATE-PER-TIER.
  byTier?: Record<string, GradeCalibrationTierEntry>;
}

// Baseline (baseball-implicit). Callers passing sport get sport-
// specific ratios via GRADE_CALIBRATION_BY_SPORT below; if the
// sport-specific cell is empty, lookupGradeRatio falls through to
// this table.
export const GRADE_CALIBRATION: Record<string, Record<string, GradeCalibrationEntry>> = {
  "bowman": {
    "BGS":  { "medianRatio": 2.26,  "p25": 1.48,  "p75": 4.30,  "sampleSize": 40 },
    "CGC":  { "medianRatio": 5.14,  "p25": 1.99,  "p75": 8.10,  "sampleSize": 71 },
    "PSA":  { "medianRatio": 4.07,  "p25": 2.28,  "p75": 8.66,  "sampleSize": 2065 },
    "SGC":  { "medianRatio": 3.73,  "p25": 1.87,  "p75": 6.37,  "sampleSize": 160 }
  },
  "bowman-chrome": {
    "BGS":  { "medianRatio": 2.28,  "p25": 1.48,  "p75": 3.82,  "sampleSize": 48 },
    "CGC":  { "medianRatio": 2.88,  "p25": 1.36,  "p75": 8.01,  "sampleSize": 31 },
    "PSA":  { "medianRatio": 3.46,  "p25": 2.15,  "p75": 7.02,  "sampleSize": 1016 },
    "SGC":  { "medianRatio": 2.19,  "p25": 1.56,  "p75": 4.23,  "sampleSize": 60 }
  },
  "bowman-chrome-draft": {
    "BGS":  { "medianRatio": 2.26,  "p25": 1.50,  "p75": 2.85,  "sampleSize": 11 },
    "PSA":  { "medianRatio": 5.32,  "p25": 2.81,  "p75": 7.35,  "sampleSize": 59 }
  },
  "bowman-sterling": {
    "PSA":  { "medianRatio": 3.00,  "p25": 1.95,  "p75": 6.30,  "sampleSize": 15 }
  },
  "panini-donruss": {
    "PSA":  { "medianRatio": 3.81,  "p25": 1.97,  "p75": 7.40,  "sampleSize": 133 },
    "SGC":  { "medianRatio": 2.92,  "p25": 1.54,  "p75": 12.63, "sampleSize": 8 }
  },
  "panini-mosaic": {
    "PSA":  { "medianRatio": 10.55, "p25": 6.27,  "p75": 29.59, "sampleSize": 10 }
  },
  "panini-optic": {
    "PSA":  { "medianRatio": 2.84,  "p25": 2.17,  "p75": 6.54,  "sampleSize": 58 }
  },
  "panini-prizm": {
    "CGC":  { "medianRatio": 4.29,  "p25": 2.21,  "p75": 6.79,  "sampleSize": 7 },
    "PSA":  { "medianRatio": 4.37,  "p25": 2.36,  "p75": 8.31,  "sampleSize": 211 }
  },
  "panini-select": {
    "PSA":  { "medianRatio": 7.96,  "p25": 4.34,  "p75": 13.38, "sampleSize": 34 }
  },
  "topps": {
    "BGS":  { "medianRatio": 3.14,  "p25": 2.01,  "p75": 5.56,  "sampleSize": 98 },
    "CGC":  { "medianRatio": 5.40,  "p25": 2.45,  "p75": 8.95,  "sampleSize": 229 },
    "PSA":  { "medianRatio": 6.44,  "p25": 3.04,  "p75": 11.73, "sampleSize": 2824 },
    "SGC":  { "medianRatio": 3.79,  "p25": 2.27,  "p75": 6.33,  "sampleSize": 270 },
    "TAG":  { "medianRatio": 3.26,  "p25": 2.05,  "p75": 9.62,  "sampleSize": 5 }
  },
  "topps-allen-ginter": {
    "CGC":  { "medianRatio": 9.55,  "p25": 3.03,  "p75": 12.71, "sampleSize": 15 },
    "PSA":  { "medianRatio": 12.39, "p25": 8.03,  "p75": 16.76, "sampleSize": 73 }
  },
  "topps-chrome": {
    "BGS":  { "medianRatio": 3.07,  "p25": 1.95,  "p75": 4.14,  "sampleSize": 25 },
    "CGC":  { "medianRatio": 6.01,  "p25": 2.91,  "p75": 8.82,  "sampleSize": 58 },
    "PSA":  { "medianRatio": 5.98,  "p25": 3.15,  "p75": 10.78, "sampleSize": 1017 },
    "SGC":  { "medianRatio": 3.95,  "p25": 2.66,  "p75": 6.14,  "sampleSize": 100 }
  },
  "topps-chrome-update": {
    "CGC":  { "medianRatio": 5.12,  "p25": 2.47,  "p75": 7.71,  "sampleSize": 20 },
    "PSA":  { "medianRatio": 6.90,  "p25": 3.67,  "p75": 11.80, "sampleSize": 235 },
    "SGC":  { "medianRatio": 2.77,  "p25": 1.83,  "p75": 4.48,  "sampleSize": 19 }
  },
  "topps-finest": {
    "BGS":  { "medianRatio": 3.01,  "p25": 2.49,  "p75": 4.77,  "sampleSize": 8 },
    "PSA":  { "medianRatio": 6.15,  "p25": 2.74,  "p75": 12.16, "sampleSize": 222 },
    "SGC":  { "medianRatio": 2.79,  "p25": 1.55,  "p75": 6.61,  "sampleSize": 10 }
  },
  "topps-heritage": {
    "CGC":  { "medianRatio": 3.30,  "p25": 2.47,  "p75": 8.80,  "sampleSize": 9 },
    "PSA":  { "medianRatio": 6.10,  "p25": 3.01,  "p75": 13.30, "sampleSize": 188 },
    "SGC":  { "medianRatio": 2.25,  "p25": 1.82,  "p75": 4.32,  "sampleSize": 11 }
  },
  "topps-pristine": {
    "PSA":  { "medianRatio": 5.80,  "p25": 2.57,  "p75": 7.19,  "sampleSize": 30 }
  },
  "topps-stadium-club": {
    "BGS":  { "medianRatio": 5.02,  "p25": 2.95,  "p75": 9.22,  "sampleSize": 6 },
    "CGC":  { "medianRatio": 3.97,  "p25": 1.34,  "p75": 5.94,  "sampleSize": 6 },
    "PSA":  { "medianRatio": 8.99,  "p25": 3.66,  "p75": 21.91, "sampleSize": 155 },
    "SGC":  { "medianRatio": 2.81,  "p25": 2.27,  "p75": 8.86,  "sampleSize": 12 }
  },
  "topps-update": {
    "BGS":  { "medianRatio": 3.13,  "p25": 2.67,  "p75": 3.56,  "sampleSize": 17 },
    "CGC":  { "medianRatio": 5.62,  "p25": 1.90,  "p75": 10.25, "sampleSize": 35 },
    "PSA":  { "medianRatio": 6.37,  "p25": 3.21,  "p75": 10.92, "sampleSize": 323 },
    "SGC":  { "medianRatio": 2.81,  "p25": 1.79,  "p75": 5.67,  "sampleSize": 39 }
  },
  "upper-deck": {
    "BGS":  { "medianRatio": 7.01,  "p25": 4.53,  "p75": 10.18, "sampleSize": 34 },
    "CGC":  { "medianRatio": 4.62,  "p25": 3.22,  "p75": 6.48,  "sampleSize": 25 },
    "PSA":  { "medianRatio": 17.38, "p25": 10.28, "p75": 24.09, "sampleSize": 343 },
    "SGC":  { "medianRatio": 5.12,  "p25": 3.32,  "p75": 9.10,  "sampleSize": 30 }
  },
  "other": {
    "BGS":  { "medianRatio": 3.33,  "p25": 1.60,  "p75": 6.00,  "sampleSize": 287 },
    "CGC":  { "medianRatio": 5.30,  "p25": 2.00,  "p75": 8.50,  "sampleSize": 506 },
    "PSA":  { "medianRatio": 5.90,  "p25": 2.50,  "p75": 11.00, "sampleSize": 9011 },
    "SGC":  { "medianRatio": 3.58,  "p25": 1.85,  "p75": 6.20,  "sampleSize": 719 },
    "TAG":  { "medianRatio": 3.26,  "p25": 2.05,  "p75": 9.62,  "sampleSize": 5 }
  }
};

// Sport-specific overlays. When lookupGradeRatio receives a sport
// argument, it prefers the entry in this table over the baseline
// above. Empty cells fall through to baseline. Regenerated by the
// per-sport calibrate script from ch_daily_sales rows filtered by
// c["group"] = sport.
export const GRADE_CALIBRATION_BY_SPORT: Record<string, Record<string, Record<string, GradeCalibrationEntry>>> = {
  baseball: {},
  football: {
    "bowman-chrome":  { "PSA": { "medianRatio": 5.05,  "p25": 4.13, "p75": 20.03, "sampleSize": 4 } },
    "panini-absolute":{ "PSA": { "medianRatio": 1.89,  "p25": 1.24, "p75": 11.67, "sampleSize": 14 } },
    "panini-chronicles":{ "PSA": { "medianRatio": 8.19, "p25": 4.63, "p75": 14.33, "sampleSize": 6 } },
    "panini-donruss": { "PSA": { "medianRatio": 3.02,  "p25": 1.59, "p75": 7.22,  "sampleSize": 177 } },
    "panini-mosaic":  { "PSA": { "medianRatio": 5.77,  "p25": 2.55, "p75": 12.05, "sampleSize": 38 } },
    "panini-optic":   { "PSA": { "medianRatio": 2.70,  "p25": 1.58, "p75": 6.36,  "sampleSize": 98 } },
    "panini-phoenix": { "PSA": { "medianRatio": 3.09,  "p25": 1.59, "p75": 8.65,  "sampleSize": 15 } },
    "panini-prizm":   {
      "PSA": { "medianRatio": 5.62, "p25": 3.56, "p75": 9.50,  "sampleSize": 124 },
      "SGC": { "medianRatio": 1.89, "p25": 1.73, "p75": 3.98,  "sampleSize": 4 }
    },
    "panini-score":   { "PSA": { "medianRatio": 7.56,  "p25": 3.36, "p75": 17.41, "sampleSize": 5 } },
    "panini-select":  { "PSA": { "medianRatio": 8.35,  "p25": 5.41, "p75": 21.52, "sampleSize": 20 } },
    "topps-chrome":   { "PSA": { "medianRatio": 4.48,  "p25": 1.86, "p75": 7.05,  "sampleSize": 14 } }
  },
  basketball: {
    "bowman-chrome":       { "PSA": { "medianRatio": 7.32,  "p25": 6.45, "p75": 20.17, "sampleSize": 4 } },
    "panini-chronicles":   { "PSA": { "medianRatio": 11.70, "p25": 6.66, "p75": 24.00, "sampleSize": 6 } },
    "panini-contenders":   { "PSA": { "medianRatio": 13.51, "p25": 2.40, "p75": 26.31, "sampleSize": 3 } },
    "panini-donruss":      {
      "PSA": { "medianRatio": 6.99, "p25": 4.41, "p75": 9.72,  "sampleSize": 38 },
      "SGC": { "medianRatio": 4.93, "p25": 2.20, "p75": 9.89,  "sampleSize": 3 }
    },
    "panini-hoops":        { "PSA": { "medianRatio": 9.34,  "p25": 4.74, "p75": 12.82, "sampleSize": 19 } },
    "panini-mosaic":       { "PSA": { "medianRatio": 6.00,  "p25": 3.51, "p75": 12.13, "sampleSize": 12 } },
    "panini-optic":        { "PSA": { "medianRatio": 6.44,  "p25": 3.64, "p75": 9.72,  "sampleSize": 24 } },
    "panini-phoenix":      { "PSA": { "medianRatio": 5.29,  "p25": 2.81, "p75": 8.03,  "sampleSize": 3 } },
    "panini-prizm":        {
      "BGS": { "medianRatio": 2.49, "p25": 2.10, "p75": 14.85, "sampleSize": 4 },
      "CGC": { "medianRatio": 2.18, "p25": 0.73, "p75": 3.00,  "sampleSize": 3 },
      "PSA": { "medianRatio": 5.00, "p25": 2.76, "p75": 8.83,  "sampleSize": 166 }
    },
    "panini-revolution":   { "PSA": { "medianRatio": 9.85,  "p25": 2.26, "p75": 39.78, "sampleSize": 4 } },
    "panini-select":       { "PSA": { "medianRatio": 4.71,  "p25": 2.63, "p75": 8.31,  "sampleSize": 23 } },
    "topps-chrome":        {
      "BGS": { "medianRatio": 2.56, "p25": 0.96, "p75": 11.67, "sampleSize": 3 },
      "PSA": { "medianRatio": 5.28, "p25": 2.71, "p75": 9.79,  "sampleSize": 88 }
    }
  },
  hockey: {},
};
