/**
 * CF-CROSS-PARALLEL-RATIOS (Drew, 2026-08-06).
 *
 * Runtime lookup for "given a same-card sibling's median price, what's
 * the estimated price of a different parallel on the same card?"
 *
 * Fallback ladder (per lookup):
 *   1. Full-parallel exact pair — "Orange Shimmer / Orange Refractor"
 *      from pool empirical data
 *   2. Same-color cross-finish — "orange: shimmer/refractor" averaged
 *      across ALL cards where both existed
 *   3. Same-finish cross-color — "refractor: orange/blue"
 *   4. Color+finish decomposition — compose the two axes: target
 *      color/source color × target finish/source finish
 *   5. null (caller falls back to next rung of the FMV ladder)
 *
 * Data source: data/cross-parallel-ratios.json, generated by
 * scripts/extract-cross-parallel-ratios.ts. Refreshed nightly by the
 * calibration job.
 *
 * All ratios point FROM source TO target — i.e. `sourceMedian × ratio
 * = targetEstimate`. If Orange Shimmer sells at $1,713 and the
 * (target=Orange Refractor, source=Orange Shimmer) ratio is 0.55, the
 * Orange Refractor estimate is $942.
 */

import * as fs from "node:fs";
import * as path from "node:path";

interface PairEntry {
  key: string;
  ratio: number;
  n: number;
  p25: number;
  p75: number;
}

interface RatioTable {
  generatedAt: string;
  windowDays: number;
  minN: number;
  fullPairs: PairEntry[];
  cfPairs: PairEntry[];
  finishPairs: PairEntry[];   // same-color cross-finish
  colorPairs: PairEntry[];    // same-finish cross-color
}

let _table: RatioTable | null | undefined = undefined;
let _fullMap: Map<string, PairEntry> | null = null;
let _cfMap: Map<string, PairEntry> | null = null;
let _finishMap: Map<string, PairEntry> | null = null;
let _colorMap: Map<string, PairEntry> | null = null;

function loadTable(): RatioTable | null {
  if (_table !== undefined) return _table;
  try {
    const p = path.resolve(process.cwd(), "data/cross-parallel-ratios.json");
    if (!fs.existsSync(p)) { _table = null; return null; }
    _table = JSON.parse(fs.readFileSync(p, "utf-8")) as RatioTable;
    _fullMap = new Map(_table.fullPairs.map((e) => [e.key, e]));
    _cfMap = new Map(_table.cfPairs.map((e) => [e.key, e]));
    _finishMap = new Map(_table.finishPairs.map((e) => [e.key, e]));
    _colorMap = new Map(_table.colorPairs.map((e) => [e.key, e]));
    return _table;
  } catch (err) {
    console.warn(`[parallelRatioLookup] load failed: ${(err as Error)?.message ?? err}`);
    _table = null;
    return null;
  }
}

// Reuse the same classifier from the extraction script. Keep in sync
// with backend/scripts/extract-cross-parallel-ratios.ts.
const COLOR_FAMILIES: Array<[string, RegExp]> = [
  ["red", /\b(red|ruby|crimson)\b/i],
  ["orange", /\b(orange|amber|tangerine)\b/i],
  ["yellow", /\b(yellow|canary)\b/i],
  ["gold", /\b(gold|golden)\b/i],
  ["green", /\b(green|emerald|forest|mint|jade)\b/i],
  ["aqua", /\b(aqua|teal|turquoise|cyan)\b/i],
  ["blue", /\b(blue|sapphire|navy)\b/i],
  ["purple", /\b(purple|violet|amethyst|lavender)\b/i],
  ["pink", /\b(pink|magenta|rose|fuchsia)\b/i],
  ["black", /\bblack\b/i],
  ["silver", /\b(silver|platinum)\b/i],
  ["white", /\bwhite\b/i],
  ["rainbow", /\brainbow\b/i],
];

const FINISH_FAMILIES: Array<[string, RegExp]> = [
  ["shimmer", /\bshimmer\b/i],
  ["ray-wave", /\b(ray\s*wave|raywave)\b/i],
  ["wave", /\bwave\b/i],
  ["lava", /\blava\b/i],
  ["lunar", /\blunar\b/i],
  ["prism", /\bprism\b/i],
  ["lazer", /\b(lazer|laser)\b/i],
  ["sapphire", /\bsapphire\b/i],
  ["geometric", /\bgeometric\b/i],
  ["sparkle", /\bsparkle\b/i],
  ["speckle", /\bspeckle\b/i],
  ["mini-diamond", /\bmini[-\s]?diamond\b/i],
  ["x-fractor", /\bx[-\s]?fractor\b/i],
  ["superfractor", /\bsuperfractor\b/i],
  ["logofractor", /\blogo(?:\s+refractor|fractor)\b/i],
  ["refractor", /\brefractor\b/i],
  ["base", /^base$/i],
];

export function classifyColor(parallel: string): string {
  const s = (parallel ?? "").toLowerCase().trim();
  for (const [name, pat] of COLOR_FAMILIES) if (pat.test(s)) return name;
  return "none";
}

export function classifyFinish(parallel: string): string {
  const s = (parallel ?? "").toLowerCase().trim();
  for (const [name, pat] of FINISH_FAMILIES) if (pat.test(s)) return name;
  return "none";
}

export interface RatioLookupResult {
  ratio: number;
  n: number;
  scope: "full-pair" | "same-color-cross-finish" | "same-finish-cross-color" | "decomposed" | "identity";
}

/** Lookup: multiply source's median by the returned ratio to estimate
 *  the target parallel's price on the same card. Returns null when no
 *  rung of the ladder has enough data. */
export function lookupParallelToParallelRatio(
  targetParallel: string | null | undefined,
  sourceParallel: string | null | undefined,
): RatioLookupResult | null {
  if (!targetParallel || !sourceParallel) return null;
  const tgt = String(targetParallel).trim();
  const src = String(sourceParallel).trim();
  if (!tgt || !src) return null;
  if (tgt.toLowerCase() === src.toLowerCase()) return { ratio: 1.0, n: Infinity, scope: "identity" };

  const table = loadTable();
  if (!table) return null;

  // Rung 1 — full-parallel exact pair (target / source).
  const fullKey = `${tgt}__${src}`;
  const full = _fullMap?.get(fullKey);
  if (full && full.ratio > 0) {
    return { ratio: full.ratio, n: full.n, scope: "full-pair" };
  }

  const tColor = classifyColor(tgt);
  const tFinish = classifyFinish(tgt);
  const sColor = classifyColor(src);
  const sFinish = classifyFinish(src);

  // Rung 2 — same-color cross-finish: e.g. orange: refractor / shimmer.
  // Only applies when both parallels share a color family.
  if (tColor === sColor && tColor !== "none") {
    const fKey = `${tColor}|${tFinish}__${sFinish}`;
    const finish = _finishMap?.get(fKey);
    if (finish && finish.ratio > 0) {
      return { ratio: finish.ratio, n: finish.n, scope: "same-color-cross-finish" };
    }
  }

  // Rung 3 — same-finish cross-color: e.g. refractor: orange / blue.
  if (tFinish === sFinish && tFinish !== "none") {
    const cKey = `${tFinish}|${tColor}__${sColor}`;
    const color = _colorMap?.get(cKey);
    if (color && color.ratio > 0) {
      return { ratio: color.ratio, n: color.n, scope: "same-finish-cross-color" };
    }
  }

  // Rung 4 — decomposition: compose color-axis and finish-axis ratios
  // via the identity finish or a common anchor. Look up
  // (targetColor, targetFinish) → some baseline via the color+finish
  // decomposed table.
  const cfTargetKey = `${tColor}:${tFinish}__${sColor}:${sFinish}`;
  const cf = _cfMap?.get(cfTargetKey);
  if (cf && cf.ratio > 0) {
    return { ratio: cf.ratio, n: cf.n, scope: "decomposed" };
  }

  return null;
}

export function ratioTableLoaded(): boolean {
  return loadTable() !== null;
}

export function ratioTableInfo(): { path: string; generatedAt?: string; loaded: boolean; totals?: { fullPairs: number; cfPairs: number; finishPairs: number; colorPairs: number } } {
  const p = path.resolve(process.cwd(), "data/cross-parallel-ratios.json");
  const table = loadTable();
  if (!table) return { path: p, loaded: false };
  return {
    path: p,
    generatedAt: table.generatedAt,
    loaded: true,
    totals: {
      fullPairs: table.fullPairs.length,
      cfPairs: table.cfPairs.length,
      finishPairs: table.finishPairs.length,
      colorPairs: table.colorPairs.length,
    },
  };
}
